### ISSUE TITLE
Duplicated instance domain while redirecting

### ISSUE THREAD

**Issue by alexbraga** [bramus/mastodon-profile-redirect#10] opened 2024-03-28 04:36 UTC
This behavior was observed while trying to redirect from `@mastodon.social`. For what I can tell, redirecting from other instances seem to be working fine (I haven't tried many, though), however redirecting from `@mastodon.social` ends up with the following URL pattern: `https://myinstance.org/@username@mastodon.socialmastodon.social`

I'm on Firefox 124.0.1
Arch Linux

**Comment by tadwohlrapp** [comment] 2024-04-16 08:38
Ran into the same issue.

I changed both of those lines:

https://github.com/bramus/mastodon-redirector/blob/5ea830c1dc4876146fc1476ebdca1663f084f5ea/src/content.js#L16
https://github.com/bramus/mastodon-redirector/blob/5ea830c1dc4876146fc1476ebdca1663f084f5ea/src/background.js#L13

to
```javascript
const userFromProfilePage = document.head.querySelector('meta[property="profile:username"]')?.content;
```

which seems to have worked. I'm not that familiar with all various versions and/or mods of mastodon, so I'll refrain from opening a PR, but maybe changing those two lines might work for some.

**Comment by ElanHasson** [comment] 2024-10-08 16:54
I've hit this also. It's a legit bug

**Comment by bramus** [comment] 2024-10-31 08:46
The reason why I don’t rely on `meta[property="profile:username"]` is that it’s not always set correctly, as reported in https://github.com/mastodon/mastodon/issues/21591. The suggested fix in https://github.com/bramus/mastodon-redirector/issues/10#issuecomment-2058550115 therefore won’t cut it.

To dig into this myself I’m gonna need a reproduction. Which steps on which URL do I need to do in order to hit this?

**Comment by wafflefin** [comment] 2024-11-02 21:18
My steps to reproduce:

1. Install Mastodon Redirector and set the LOCAL_DOMAIN to nyan.lol and leave the WEB_DOMAIN blank.
2. Visit https://journa.host/@AdminTeam and click Mastodon Redirector
3. Tab navigates to https://nyan.lol/@AdminTeam@journa.hostjourna.host

Expected result: Tab navigates to https://nyan.lol/@AdminTeam@journa.host

Note: https://journa.host/@AdminTeam/111216986599770977 successfully navigates to https://nyan.lol/@AdminTeam@journa.host/111216986586742664.

**Comment by PeskyPotato** [comment] 2024-12-27 09:02
Similar results to @wafflefin, redirecting from profiles does not work but posts do. I have `LOCAL_DOMAIN` set to `hachyderm.io` and `WEB_DOMAIN` blank.


Some profile examples that do not work:
- https://journa.host/@AdminTeam redirects to https://hachyderm.io/@AdminTeam@journa.hostjourna.host
- https://social.overheid.nl/@knmi redirects to https://hachyderm.io/@knmi@social.overheid.nlsocial.overheid.nl
- https://mastodon.social/@Mastodon redirects to https://hachyderm.io/@Mastodon@mastodon.socialmastodon.social

Some profile examples that do work:
- https://digipres.club/@foone redirects to https://hachyderm.io/@foone@digipres.club
- https://zug.network/@RensBloom redirects to https://hachyderm.io/@RensBloom@zug.network

Redirecting from posts work fine, for example:
- https://ec.social-network.europa.eu/@EUCommission/113723890623008924 redirects to https://hachyderm.io/@EUCommission@ec.social-network.europa.eu/113723892188197237

Hope this helps.

**Comment by PeskyPotato** [comment] 2024-12-27 15:23
I've done some digging, in Mastodon v4.3.x and v4.4.x there's an UI change which results in the profile redirects not working. The query selector picks up the instance domain twice, once for the invisible text and the second for the visible text on screen. The extension works fine for the two other profiles I listed because those servers are still running v4.2.x.

Here's the current query selector:

https://github.com/bramus/mastodon-redirector/blob/5ea830c1dc4876146fc1476ebdca1663f084f5ea/src/background.js#L13
https://github.com/bramus/mastodon-redirector/blob/5ea830c1dc4876146fc1476ebdca1663f084f5ea/src/content.js#L16

I've tested the following code snippet which works with the new (>= v4.3.x) and old (v4.2.x) UI. You can test this from the browser console on Mastodon profiles:

```javascript
const userFromProfilePage = document.querySelector('.account__header .account__header__tabs__name small')?.innerText.split('\n');
if (userFromProfilePage) {
    if (userFromProfilePage.length == 1) {
        console.log(userFromProfilePage[0].substring(1));
    }
    else if (userFromProfilePage.length == 3) {
        console.log(userFromProfilePage[0].substring(1) + userFromProfilePage[1]);
    }
}
```
Posts and moved account seem unaffected between different version, I've only done a quick check. Feel free to use this code or the information I've written above in a PR.

**Comment by PeskyPotato** [comment] 2024-12-27 16:11
Created a PR (#12) so others can test, ran it through a number of profiles on my feed and seems to work across profile pages from v4.2.x, v4.3.x and v4.4.x.

**Comment by bramus** [comment] 2024-12-27 18:26
Thanks for digging in and filing the PR. I merged #12 and will publish a new version soon.

**Closed as completed by bramus** 2024-12-27 18:26 UTC

**Comment by bramus** [comment] 2024-12-28 19:54
Version 0.4.1. was submitted to the Extension “App Stores” just now.

**Comment by PeskyPotato** [comment] 2024-12-29 08:44
Thank you @bramus for the quick reply and action!
